spring.application.name=RAG
server.port=8080

# ???????????????????????????????????????
#           DATABASE - MySQL
# ???????????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/RagApplication_DB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Shunmuga@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ???????????????????????????????????????
#           JPA / HIBERNATE
# ???????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ???????????????????????????????????????
#           FILE UPLOAD
# ???????????????????????????????????????
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ???????????????????????????????????????
#           GROQ API KEY
# ???????????????????????????????????????
groq.api.key=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

# ???????????????????????????????????????
#           LOGGING
# ???????????????????????????????????????
logging.level.com.AiProject.RAG=DEBUG
logging.level.dev.langchain4j=DEBUG
logging.level.org.springframework.security=DEBUG